### ISSUE TITLE
Load Trackers from a Textfile

### ISSUE THREAD

**Issue by HighnessAtharva** [Not-Quite-RARBG/main#17]
Use PHP server side logic to read from a text file and generate a list of trackers instead of outputting raw html. The below code block needs to be changed. Will save space, cleanup code and help add more trackers easily in the future.

https://github.com/Not-Quite-RARBG/main/blob/92c6ea2ffd9ae3b124cd6563d107881a1897ad31/torrent/index.php#L151

**Comment by AnonymousWP** [comment]
This is a great starting point: https://github.com/ngosang/trackerslist 😉

**Comment by HighnessAtharva** [comment]
> This is a great starting point: [ngosang/trackerslist](https://github.com/ngosang/trackerslist). 😉 Automatically updated every day.

Perfect resource.

**Comment by SlideMovies** [comment]
Will add A.S.A.P.

**Comment by SlideMovies** [comment]
Fixed with: https://github.com/Not-Quite-RARBG/main/commit/627d7df9fc71ae66a85d7304cdd54d7d1cdc74e8, https://github.com/Not-Quite-RARBG/main/commit/a473df5ebd1543c98a6e2697a8f551ea24049010, and https://github.com/Not-Quite-RARBG/main/commit/43a9a03c48b59cb1820f42b554b5a66f155a78b7
