### ISSUE TITLE
If IMDB ID doesn't exist, don't show the empty elements

### ISSUE THREAD

**Issue by ejach** [Not-Quite-RARBG/main#22]
If the IMDB ID doesn't exist, don't show these empty elements.
<img width="911" alt="image" src="https://github.com/Not-Quite-RARBG/main/assets/42357644/6c62c63b-9823-47b6-8cd6-12a85cb06598">

**Comment by ejach** [comment]
Fixed when #19 merges.

**Comment by SlideMovies** [comment]
Merged.
