### ISSUE TITLE
the discord link is...

### ISSUE THREAD

**Issue by ICE-COOL-LEMONADE** [Not-Quite-RARBG/main#25]
![1300498036880](https://github.com/Not-Quite-RARBG/main/assets/42024522/42c4ab24-4d12-46f3-9f66-53cc4b23dea1)

**Comment by Paheyin** [comment]
...expired.

**Comment by THGhost** [comment]
![giphy](https://github.com/Not-Quite-RARBG/main/assets/32550606/6cab2eb6-f971-4364-a83b-14979d630988)

**Comment by MathiasDevelopes** [comment]
> ...expired.
They are planning to use divolt, so discord invites are disabled. See the comment in #23.

**Comment by THGhost** [comment]
> > ...expired.
> 
> They are planning to use divolt, so discord invites are disabled. See the comment in #23.

They should probably remove the discord invite link from the main page then, no?

**Comment by MathiasDevelopes** [comment]
> > > ...expired.
> > 
> > 
> > They are planning to use divolt, so discord invites are disabled. See the comment in #23.
> 
> They should probably remove the discord invite link from the main page then, no?

Yes, they should remove it, to stop issues about the discord link.

**Comment by MathiasDevelopes** [comment]
> > > ...expired.
> > 
> > 
> > They are planning to use divolt, so discord invites are disabled. See the comment in #23.
> 
> They should probably remove the discord invite link from the main page then, no?

I have created a pull request to remove the broken discord link, see #27

**Comment by THGhost** [comment]
> > > > ...expired.
> > > 
> > > 
> > > They are planning to use divolt, so discord invites are disabled. See the comment in #23.
> > 
> > 
> > They should probably remove the discord invite link from the main page then, no?
> 
> I have created a pull request to remove the broken discord link, see #27

Good. Now we just need the site to work. I'm assuming it's getting a lot of traffic.
