### ISSUE TITLE
Move to self hosted Git service instead of GitHub

### ISSUE THREAD

**Issue by ggtylerr** [Not-Quite-RARBG/main#31]
While the repo doesn't contain any copyrighted content (and presumably won't have any), it's a good idea to switch out of GitHub since it very easily could be taken down.

Some top contenders (IMO) include:
* [SourceHut](https://sr.ht/~sircmpwn/sourcehut/) - Early development, but already very functional and promising
* [Forgejo](https://forgejo.org/) - Closest project to GitHub's design (Used by Codeberg)
* [GitLab](https://gitlab.com/gitlab-org/gitlab-foss/) - Biggest contender to GitHub, although they're definitely the weakest out of the 3

It also goes without saying, while it's possible to host them on the main services listed, it won't solve the full problem and it's better to self-host it (even if this means it'll take a few more server resources.)

**Comment by SlideMovies** [comment]
will host it soon

**Comment by SlideMovies** [comment]
Won't be switching from GitHub, we might however, if this repo gets a DMCA takedown request.
Till then we will host a mirror for this repo.
