### ISSUE TITLE
PRIDEIFY** the LOGO!!!!!!!

### ISSUE THREAD

**Issue by ICE-COOL-LEMONADE** [Not-Quite-RARBG/main#33]
![rarbg-crop](https://github.com/Not-Quite-RARBG/main/assets/42024522/c6996c5b-b272-42ba-ad32-a080da202ea0)

**PRIDE™ is a registered trademark of Cohen & Feldstein Petrochem PharmaSYS, Financial and Investment Holdings Corporation, inc (herein "C&F"). C&F will not be held responsible for any injuries or losses sustained while partaking in PRIDE™ activities. including but not limited to, internal injuries, transmissible diseases, loss of items though insertion.

**Comment by SlideMovies** [comment]
no need
