### ISSUE TITLE
Warning about api.consumet.org

### ISSUE THREAD

**Issue by wearrrrr** [Not-Quite-RARBG/main#39]
Hello! I am an active contributor for the consumet API and Consumet TS library, I'm just here to let you know that the official api.consumet.org url WILL be shutting down in the next couple months, the packages will obviously still be maintained, just a public instance will no longer be available. I'd highly recommend you find a way to host your own, as it will not be around forever, hopefully you are already doing this, but for anyone self hosting who isn't, please begin migrating!!

**Comment by SlideMovies** [comment]
I already have a self-hosted instance.

**Comment by SlideMovies** [comment]
I'll add this notice to the readme

**Comment by wearrrrr** [comment]
Great! Thank you 😊
