### ISSUE TITLE
bug(scope): Is this dead ?

### ISSUE THREAD

**Issue by Kaneki010** [Not-Quite-RARBG/main#59]
### Current Behavior

no updates

### Expected Behavior

updates

### Steps To Reproduce

look at the github repository

### Environment

```markdown
- **OS**:
- **Browser**:
```

**Comment by AnonymousWP** [comment]
No, the project is not dead. It's just that the developer(s) are busy with private things in life. Next week onwards, they can work on NQ-RARBG again.
